# Welcome to Jekyll!
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Joseph Howlett
subtitle: Dark Matter Researcher
email: Joseph.J.Howlett@gmail.com, joseph.howlett@columbia.edu
description: >- # this means to ignore newlines until "baseurl:"
  A bit about me
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  JosephJHowlett

author:
  name: "Joseph Howlett"
  avatar: "/assets/images/muon/IMG_6073.JPG"
  bio: "*I am a dark matter hunter at Columbia University*" # Note: Markdown is allowed
  location: "New York, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JosephJHowlett"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joseph-howlett-a180471b7/"

atom_feed:
  hide: true


# Build settings
#theme: jekyll-theme-merlot
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "dirt"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   
paginate: 0

paginate_path: /page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
